ERP_College/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

# Basic Login
urlpatterns += [
    url(r'^login/$', auth_views.login,{'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]


# API urls
# urlpatterns += [
#     url(r'^api/', include(api.urls))
# ]


# ModuleCommon
urlpatterns += [
    url(r'^', include('ModuleCommon.urls', namespace='module_common')),
]


# ModuleStudent
urlpatterns += [
    url(r'^student/', include('ModuleStudent.urls', namespace='module_student')),
]


# ModuleTeacher
urlpatterns += [
    url(r'^teacher/', include('ModuleTeacher.urls', namespace='module_teacher')),
]

# ModuleAdmin
urlpatterns += [
    url(r'^administrator/', include('ModuleAdmin.urls', namespace='module_admin')),
]

# ModuleAdmin
urlpatterns += [
    url(r'^reports/', include('ModuleReports.urls', namespace='module_reports')),
]

ModuleCommon/urls.py
from django.conf.urls import url
from .views import HomeView
from tastypie.api import Api

# Normal Url
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='common-home'),

    # url(r'attorney/$', AttorneyListView.as_view(), name='attorney-list'),
    # url(r'^attorney/(?P<slug>[-_\w]+)/$', AttorneyDetailView.as_view(), name='attorney-detail'),
]

ModuleReports/urls.py
from django.conf.urls import url
from .views import ReportQualifications, EnrollmentReport

# Normal Url
urlpatterns = [
    url(r'^qualifications/(?P<id>\d+)$', ReportQualifications.as_view(), name='report-qualifications'),

    url(r'^enrollment/(?P<id>\d+)$', EnrollmentReport.as_view(), name='enrollment-report'),

]

ModuleStudent/urls.py
from django.conf.urls import url
from .views import StudentQualifications

# Normal Url
urlpatterns = [
    url(r'^qualifications', StudentQualifications.as_view(), name='student-qualifications'),
]

ModuleReports/views.py
from re import split

from django.http import HttpRequest
from django.shortcuts import render
from ModuleCommon.models import Qualification
from django.views import View
import  json
import requests
from decimal import Decimal
from ERP_College.settings import WEBService


class ReportQualifications(View):
    template = 'ModuleReports/report-qualifications.html'

    def get(self, request, *args, **kwargs):

        subject = requests.get(WEBService + 'subject')
        subject = subject.json()
        quali = requests.get(WEBService+'quali_id/'+kwargs['id']+'/')
        quali = quali.json()
        student = requests.get(WEBService+'student_id/'+kwargs['id']+'/')
        student = student.json()
        enrollment = requests.get(WEBService+'enrollment_st/'+kwargs['id']+'/')
        enrollment = enrollment.json()
        grade = requests.get(WEBService+'grade/'+str(enrollment['grade'])+'/')
        grade = grade.json()
        teacher = requests.get(WEBService+'teacher_id/'+str(grade['teacher'])+'/')
        teacher = teacher.json()
        for qua in quali:
            print(qua)
        quali_ = []
        qualis = []
        i = 0
        for ll in subject:
            quali_ =[{'id': ll['id'],
                      'name': ll['name'],
                         'ps': '',
                         'pf': '',
                         }]


            o = 0

            while o < 10:
                o += 1
                quali_[i][o] = ''

            for qua in quali:
                if qua['teacher_subject'] == ll['id']:
                    quali_[i][qua['position']] = qua['value']

            o = 0
            sm = 0
            pm = 0
            while o < 10:
                o += 1
                if quali_[i][o] != '':
                    sm += Decimal(quali_[i][o])
                    pm += 1
            if pm != 0:
                quali_[i]['ps'] = round(float(sm / pm), 1)
                quali_[i]['pf'] = round(float(sm / pm), 1)

            #i += 1
            print('i ='+str(i))
            qualis+=quali_
        i=0
        su=0
        for lk in qualis:
            if lk['ps']!='':
                su+= Decimal(lk['ps'])
                i+=1
            print(lk)
        su= round(float(su / i), 1)
        print(su)
        return render(request, self.template, locals())



class EnrollmentReport(View):
    template = 'ModuleReports/enrollment.html'

    def get(self, request, *args, **kwargs):
        print(kwargs['id'])

        enrollment = requests.get(WEBService + 'enrollment' + '/' + kwargs['id'])
        enrollment = enrollment.json()
        student = requests.get(WEBService + 'student_id' + '/' + str(enrollment['student']))
        student = student.json()
        attorney = requests.get(WEBService + 'attorney_id' + '/' + str(student['attorney']))
        attorney = attorney.json()
        date = split('T', enrollment['created_at'])
        date = date[0]
        grade = requests.get(WEBService + 'grade' + '/' + str(enrollment['grade']))
        return render(request, self.template, locals())

templates/ModuleReports/components/menu.html
{% url 'module_common:common-home' as common_home_url %}
{% url 'module_student:student-qualifications' as qualifications_url %}






<div class="menu">
    <div class="card card-menu {% if request.path == common_home_url %}active{% endif %}">
        <a href="{% url 'module_common:common-home' %}">
            <div class="card-body row">
                <div class="col-lg-3">
                    <i class="material-icons md-2x">view_quilt</i>
                </div>
                <div class="col-lg-9">
                    <p><strong>Mi Muro</strong></p>
                </div>
            </div>
        </a>
    </div>

    <div class="card card-menu">
        <a href="">
            <div class="card-body row">
                <div class="col-lg-3">
                    <i class="material-icons md-2x">event</i>
                </div>
                <div class="col-lg-9">
                    <p><strong>Mi Horario</strong></p>
                </div>
            </div>
        </a>
    </div>

    <div class="card card-menu {% if request.path == qualifications_url %}active{% endif %}">
        <a href="{% url 'module_student:student-qualifications' %}">
            <div class="card-body row">
                <div class="col-lg-3">
                    <i class="material-icons md-2x">assignment</i>
                </div>
                <div class="col-lg-9">
                    <p><strong>Mis Notas</strong></p>
                </div>
            </div>
        </a>
    </div>

    <div class="card card-menu">
        <a href="">
            <div class="card-body row">
                <div class="col-lg-3">
                    <i class="material-icons md-2x">assignment_turned_in</i>
                </div>
                <div class="col-lg-9">
                    <p><strong>Mi Asistencia</strong></p>
                </div>
            </div>
        </a>
    </div>



{#    if apoderado habilitar anotaciones#}

</div>