ERP_College/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

# Basic Login
urlpatterns += [
    url(r'^login/$', auth_views.login,{'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]


# API urls
# urlpatterns += [
#     url(r'^api/', include(api.urls))
# ]


# ModuleCommon
urlpatterns += [
    url(r'^', include('ModuleCommon.urls', namespace='module_common')),
]


# ModuleStudent
urlpatterns += [
    url(r'^student/', include('ModuleStudent.urls', namespace='module_student')),
]


# ModuleTeacher
urlpatterns += [
    url(r'^teacher/', include('ModuleTeacher.urls', namespace='module_teacher')),
]

# ModuleAdmin
urlpatterns += [
    url(r'^administrator/', include('ModuleAdmin.urls', namespace='module_admin')),
]

# ModuleAdmin
urlpatterns += [
    url(r'^reports/', include('ModuleReports.urls', namespace='module_reports')),
]

ModuleAdmin/urls.py
from django.conf.urls import url
from .views import AdminGrades, AdminSubjects, AdminTeachers, AdminStudents, AdminAdmissionAttorney,\
    AdminAdmissionStudentSet, AdminAdmissionAttorneySet, AdminAdmissionStudent, AdminAdmissionenRollment

urlpatterns = [
    url(r'^grades', AdminGrades.as_view(), name='grades'),
    url(r'^subjects', AdminSubjects.as_view(), name='subjects'),
    url(r'^tachers', AdminTeachers.as_view(), name='teachers'),
    url(r'^students', AdminStudents.as_view(), name='students'),
    url(r'^admission/$', AdminAdmissionAttorney.as_view(), name='admission_attorney'),
    url(r'^admission/(?P<rut>[a-z0-9,-]+)$', AdminAdmissionAttorneySet.as_view(), name='admission_attorney_set'),
    url(r'^student/(?P<rut>[a-z0-9,-]+)/$', AdminAdmissionStudent.as_view(), name='admission_student'),
    url(r'^student/(?P<rut>[a-z0-9,-]+)/(?P<student>[a-z0-9,-]+)/$', AdminAdmissionStudentSet.as_view(), name='admission_student_set'),
    url(r'^enrollment/(?P<rut>[a-z0-9,-]+)/(?P<student>[a-z0-9,-]+)/$', AdminAdmissionenRollment.as_view(), name='admission_enrollment_set'),
]

ModuleReports/urls.py
from django.conf.urls import url
from .views import ReportQualifications, EnrollmentReport

# Normal Url
urlpatterns = [
    url(r'^qualifications/(?P<id>\d+)$', ReportQualifications.as_view(), name='report-qualifications'),

    url(r'^enrollment/(?P<id>\d+)$', EnrollmentReport.as_view(), name='enrollment-report'),

]

ModuleAdmin/models.py
from django.db import models

# crear modelos solo si es necesario

ModuleCommon/models.py
from django.db import models
from django.contrib.auth.models import User



class Grade(models.Model):
    name = models.CharField(max_length=50, null=False)
    number = models.IntegerField(null=False)
    latter = models.CharField(max_length=1, null=True)
    level = models.CharField(max_length=20, null=True)
    def __str__(self):
        return self.name+' '+self.latter+' ' + self.level


class Person(models.Model):
    rut = models.CharField(max_length=10, unique=True)
    first_name = models.CharField(max_length=30, null=False)
    last_name = models.CharField(max_length=30, null=False)
    gender = models.CharField(max_length=20, null= False)
    address = models.CharField(max_length=100, null=False)
    email = models.EmailField(null=True)
    birthdate = models.DateField(null=False)
    age = models.IntegerField(null=True)
    phone = models.IntegerField(null=True)
    cellphone = models.IntegerField(null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
          abstract = True



class Attorney(Person):
     # custom fields
     def __str__(self):
         return self.rut


class Student(Person):
    attorney = models.ForeignKey(Attorney, null=False, blank=True, on_delete=models.CASCADE)
    #matricula = models.ForeignKey()
    grade = models.ForeignKey(Grade, null=False, blank=True, on_delete=models.CASCADE)

    def __str__(self):
         return self.rut
#
#
class Teacher(Person):
     #custom fields

     def __str__(self):
         return self.rut
#
#
# class Administrative(Person):
#     # custom fields
#
#     def __str__(self):
#         return self.rut

class Subject(models.Model):
    name = models.CharField(max_length=50, null=False)
    specialty = models.CharField(max_length=50, null=False)
    def __str__(self):
        return self.name


class Teacher_Subject(models.Model):
    subject = models.ForeignKey(Subject, null=False, blank=True, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, null=False, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.subject.name+' - '+self.teacher.first_name+' '+self.teacher.last_name

class Qualification(models.Model):
    value = models.DecimalField(max_digits=2, decimal_places=1, blank=True, null=True)
    position = models.IntegerField(null=False)
    teacher_subject = models.ForeignKey(Teacher_Subject, null=False, blank=True, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, null=False, blank=True, on_delete=models.CASCADE)
    period = models.IntegerField(null=False)
    def __str__(self):
        return str(self.value)

class Enrollment(models.Model):
    rode = models.IntegerField(null=False)
    tariff = models.IntegerField(null=False)
    monthly= models.IntegerField(null=False)
    total= models.IntegerField(null=False)
    remaining= models.IntegerField(null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    grade = models.IntegerField(null=False)
    period = models.IntegerField(null=False)
    student = models.IntegerField(null=False)
    payment = models.IntegerField(null=False)

ModuleAdmin/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from  .forms import AttorneyForm, RutForm, EnrollmentForm
from django.utils import timezone
import  json, requests
from ERP_College.settings import WEBService

class AdminGrades(View):
    template = 'ModuleAdmin/grades.html'

    def get(self, request):
        return render(request, self.template, locals())

class AdminSubjects(View):
    template = 'ModuleAdmin/subjects.html'

    def get(self, request):
        return render(request, self.template, locals())

class AdminTeachers(View):
    template = 'ModuleAdmin/teachers.html'

    def get(self, request):
        return render(request, self.template, locals())

class AdminStudents(View):
    template = 'ModuleAdmin/students.html'
    select = 'student/'
    def get(self, request):
        list = requests.get(WEBService+self.select)
        data = list.json()
        print(data)
        return render(request, self.template, locals())

class AdminAdmissionAttorney(View):
    template = 'ModuleAdmin/admissionattorney.html'

    def get(self, request, *args, **kwargs):
        form = RutForm()
        self.template = 'ModuleAdmin/admissionattorney.html'
        return render(request, self.template, locals())

    def post(self, request, **kwargs):
        form = AttorneyForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            print(obj.birthdate.day)
            set_data='{"rut":"'+obj.rut+'",' \
                    ' "first_name": "'+obj.first_name+'",' \
                    '"last_name": "'+obj.last_name+'",' \
                    '"gender": "'+obj.gender+'",' \
                    '"address": "'+obj.address+'",' \
                    '"email": "'+obj.email+'",' \
                    '"birthdate": "2007-09-26",' \
                    '"age": '+str(obj.age)+',' \
                    '"phone": '+str(obj.phone)+',' \
                    '"cellphone": '+str(obj.cellphone)+'}'

            set_data=json.loads(set_data)
            requests.post(WEBService+'attorney/', data=set_data)
            #form.save()
            return redirect('module_admin:admission_student', pk=obj.rut)
        else:
            print(form.is_valid())
            print(form.errors)
            form = AttorneyForm(request.POST)
        return render(request, self.template, locals())

class AdminAdmissionAttorneySet(View):
    template = 'ModuleAdmin/admissionattorney.html'
    def get(self, request, *args, **kwargs):
        rut = kwargs['rut']
        print(rut)
        atto = requests.get(WEBService+'attorney/'+rut)

        print(atto)
        atto = atto.json()
        print(atto)
        if atto != {'detail': 'Not found.'}:
            data ={'rut': atto['rut'],
                    'first_name' : atto['first_name'],
                    'last_name' : atto['last_name'],
                    'email': atto['email'],
                    'birthdate': atto['birthdate'],
                    'gender' : atto['gender'],
                    'address': atto['address'],
                    'phone': atto['phone'],
                    'cellphone' : atto['cellphone'],
                    'age': atto['age'],
                   }
            print(data)
        form = AttorneyForm()
        return render(request, self.template, locals())

    def post(self, request, **kwargs):
        rut = kwargs['rut']
        form = AttorneyForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            print(obj.birthdate.year)
            print(timezone.now().year)
            age=timezone.now().year - obj.birthdate.year
            print(age)
            date=str(obj.birthdate)
            set_data='{"rut":"'+obj.rut+'",' \
                    ' "first_name": "'+obj.first_name+'",' \
                    '"last_name": "'+obj.last_name+'",' \
                    '"gender": "'+obj.gender+'",' \
                    '"address": "'+obj.address+'",' \
                    '"email": "'+obj.email+'",' \
                    '"birthdate": "'+date+'",' \
                    '"age": '+str(age)+',' \
                    '"phone": '+str(obj.phone)+',' \
                    '"cellphone": '+str(obj.cellphone)+'}'

            set_data=json.loads(set_data)

            ll = requests.post(WEBService+'attorney/'+obj.rut+'/', data=set_data)
            if ll.json()['rut'] == ['attorney with this rut already exists.']:
                ll = requests.put(WEBService+'attorney/'+obj.rut+'/', data=set_data)
            obj= None
            return redirect('module_admin:admission_student', rut=rut)
        else:
            print(form.is_valid())
            print(form.errors)
            form = AttorneyForm(request.POST)
        return render(request, self.template, locals())

class AdminAdmissionStudent(View):
    template = 'ModuleAdmin/admissionstudents.html'

    def get(self, request, *args, **kwargs):
        rut_a = kwargs['rut']
        form = RutForm()
        return render(request, self.template, locals())

class AdminAdmissionStudentSet(View):
    template = 'ModuleAdmin/admissionstudents.html'
    select = 'student'
    def get(self, request, *args, **kwargs):
        rut_a = kwargs['rut']
        rut_s= kwargs['student']
        print(rut_a+' - '+rut_s+' -> '+WEBService+self.select+'/'+rut_s)
        atto = requests.get(WEBService+self.select+'/'+rut_s)
        atto = atto.json()
        print(atto)
        if atto != {'detail': 'Not found.'}:
            """
            data ={'rut': atto['rut'],
                    'first_name' : atto['first_name'],
                    'last_name' : atto['last_name'],
                    'email': atto['email'],
                    'birthdate': atto['birthdate'],
                    'gender' : atto['gender'],
                    'address': atto['address'],
                    'phone': atto['phone'],
                    'cellphone' : atto['cellphone'],
                    'age': atto['age'],
                    'attorney' : atto['attorney']
                   } """
            data=atto
            print(data)
        form = AttorneyForm()
        return render(request, self.template, locals())

    def post(self, request, **kwargs):
        rut = kwargs['rut']
        student= kwargs['student']
        form = AttorneyForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            age=timezone.now().year - obj.birthdate.year
            attorney = requests.get(WEBService + 'attorney' + '/' + rut)
            attorney = attorney.json()
            attorney=str(attorney['id'])
            grade=1
            date=str(obj.birthdate)
            set_data='{"rut":"'+obj.rut+'",' \
                    ' "first_name": "'+obj.first_name+'",' \
                    '"last_name": "'+obj.last_name+'",' \
                    '"gender": "'+obj.gender+'",' \
                    '"address": "'+obj.address+'",' \
                    '"email": "'+obj.email+'",' \
                    '"birthdate": "'+date+'",' \
                    '"age": '+str(age)+',' \
                    '"phone": '+str(obj.phone)+',' \
                    '"cellphone": '+str(obj.cellphone)+','\
                    '"attorney": '+str(attorney)+'}'
            print(set_data)
            set_data=json.loads(set_data)
            ll = requests.post(WEBService+self.select+'/'+student+'/', data=set_data)
            print(WEBService+self.select+'/'+student+'/')
            print(ll.json())
            if ll.json()['rut'] == ['student with this rut already exists.']:
                ll = requests.put(WEBService+self.select+'/'+student+'/', data=set_data)
                print(ll.json())
            return redirect('module_admin:admission_enrollment_set', rut=rut, student=student)
        else:
            print(form.is_valid())
            print(form.errors)
            form = AttorneyForm(request.POST)
        return render(request, self.template, locals())

class AdminAdmissionenRollment(View):
    template = 'ModuleAdmin/admissionenrollment.html'

    def get(self, request, *args, **kwargs):
        form = EnrollmentForm()
        now = timezone.now().date()
        print(form)
        grade = requests.get(WEBService+'grade/')
        grade=grade.json()
        return render(request, self.template, locals())

    def post(self, request, **kwargs):
        form = EnrollmentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            student=kwargs['student']
            student = requests.get(WEBService + 'student' + '/' + student)
            student = student.json()
            student=str(student['id'])
            grade = requests.get(WEBService + 'grade' + '/' + str(obj.grade))
            grade = grade.json()
            grade = str(grade['id'])
            set_data = '{"rode":"' + str(obj.rode) + '",' \
                    ' "tariff": "'+str(obj.tariff)+'",' \
                    ' "total": "'+str(obj.total)+'",' \
                    ' "monthly": "'+str(obj.monthly)+'",' \
                    ' "remaining": "'+str(obj.remaining)+'",' \
                    ' "grade": "'+grade+'",' \
                    ' "period": "'+str(obj.period)+'",' \
                    ' "student": "'+student+'",' \
                    ' "payment": '+str(obj.payment)+'}'

            set_data=json.loads(str(set_data))
            ll=requests.post(WEBService+'enrollment/', data=set_data)
            ll= ll.json()
            #form.save()
            return redirect('module_reports:enrollment-report', id=ll['id'])
        else:
            print(form.is_valid())
            print(form.errors)
            form = EnrollmentForm(request.POST)
            #return redirect('module_admin:admission_enrollment_set', rut=kwargs['rut'], student=kwargs['student'])

            return render(request, self.template, locals())

templates/ModuleAdmin/admissionattorney.html
{% extends 'base.html' %}

{% block content %}
    {# siempre lg-7#}

    <script type='text/javascript'>
        $(document).ready(function(){

            $('#id_rut').blur(function(){

                var rut= $("#id_rut");
                if(rut.val().length > 8) {
                    window.location.href = "{% url 'module_admin:admission_attorney' %}"+rut.val();
                     return false;
                }else {

                    alert("El nombre debe tener como mínimo 9 caracteres");
                }


            });
        });
        $(document).ready(function(){
            $('#reload').click(function(){
                var rut= $("#id_rut");
                if(rut.val().length > 8) {
                    window.location.href = "{% url 'module_admin:admission_attorney' %}"+rut.val();
                     return false;
                }else {

                    alert("El nombre debe tener como mínimo 9 caracteres");
                }



            });
        });
    </script>

    <div class="col-lg-7">
        <h1>Matricula.</h1>
        <div class="wall">

        <div class="card">
            <div class="card-body row">
                    <div class="col-lg-2">
                        <img class="img-wall img-fluid rounded-circle mx-auto d-block" src="https://www.flaticon.es/premium-icon/icons/png/512/547/547479.png">
                    </div>

                    <div class="col-lg-10">
                        <form method="POST">
                            {% csrf_token %}
                           <h4>Datos del Apoderado.</h4>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>Rut :</label>
                                    <input type="text" name="rut" value="{{ rut }}" hidden required class="form-control" minlength="9" maxlength="10" />

                                    {% if data.rut %}
                                        <input type="text" name="rut" value="{{ data.rut }}" disabled required id="id_rut" class="form-control" maxlength="10" />
                                    {% else %}
                                        <input type="text" name="rut" value="{{ rut }}" maxlength="10" minlength="9" placeholder="Ej: 11111111-1" {% if rut %} disabled {% endif %} id="id_rut" class="form-control" />
                                    {% endif %}
                                </div>
                                <div class="col-lg-2" align="center">
                                    {% if rut == None %}
                                        <div style="padding-top: 32px">
                                            <img height="30" width="30" src="https://image.flaticon.com/icons/svg/189/189687.svg" id="reload" style="cursor: pointer">
                                        </div>
                                    {% else %}
                                        <div style="padding-top: 32px">
                                            <a class="hidden-xs-down" href="{% url 'module_admin:admission_attorney' %}"> <img height="30" width="30" src="https://image.flaticon.com/icons/svg/189/189675.svg" id="reload" style="cursor: pointer"></a>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-lg-4" style="padding-top: 20px">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>Nombre:</label>
                                    <input type="text" name="first_name" required id="id_first_name" placeholder="Juan" {% if rut == None %} disabled {% endif %} value="{{ data.first_name }}" class="form-control" maxlength="30" />
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label>Apellidos:</label>
                                    <input type="text" name="last_name" maxlength="30" class="form-control" id="id_first_name"  {% if rut == None %} disabled {% endif %} value="{{ data.last_name }}" placeholder="Ej. Perez Soto" required />
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>Fecha de nacimiento:</label>
                                    <input type="date" name="birthdate"  class="form-control" id="id_birthdate" required {% if rut == None %} disabled {% endif %} value="{{ data.birthdate }}"/>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label>Genero:</label><br>
                                    {% if data.rut %}
                                        <input type="radio" name="gender" value="male"  {% if data.gender == 'male' %} checked {% endif %}> Masculino<br>
                                        <input type="radio" name="gender" value="female"{% if data.gender == 'female' %} checked {% endif %}> Femenino
                                    {% else %}
                                        <input type="radio" name="gender" value="male" checked > Masculino<br>
                                        <input type="radio" name="gender" value="female"> Femenino
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>Direccion:</label>
                                    <input type="text" name="address" maxlength="100"  class="form-control" id="id_address" {% if rut == None %} disabled {% endif %} value="{{ data.address }}"  placeholder="Ej. Santo Domingo 23, santiago" required />
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label>E-mail de contacto:</label>
                                    <input type="email" name="email" maxlength="254" class="form-control" id="id_email" placeholder="Ej. example@dominio.cl" {% if rut == None %} disabled {% endif %} value="{{ data.email }}"  required />
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>Telefono de contacto:</label>
                                    <input type="number" name="phone" maxlength="12" class="form-control" id="id_phone" placeholder="Ej. 23232343" {% if rut == None %} disabled {% endif %} value="{{ data.phone }}"  required />
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label>Celular de contacto:</label>
                                    <input type="number" name="cellphone" maxlength="12" class="form-control" id="id_cellphone" placeholder="Ej. 95432343" {% if rut == None %} disabled {% endif %} value="{{ data.cellphone }}"  required />
                                </div>
                            </div>

                            <div class="row" style="padding-top: 3%">
                                {% if data.rut %}
                                    <input type="text" name="age" required id="id_age"  class="form-control" value="{{ data.age }}" hidden />
                                {% else %}
                                    <input type="text" name="age" required id="id_age"  class="form-control" value="0" hidden />
                                {% endif %}
                                <div class="col-lg-12" align="right">
                                    <a href="javascript:history.back()"> <button type="button" class="btn btn-info">Volver</button></a>
                                    <span style="padding-right: 5%"></span>
                                    <input type="submit" class="btn btn-primary" value="Continuar" >
                                </div>
                            </div>
                        </form>
                 </div>
            </div>
        </div>


    </div>
    </div>


{% endblock content %}

templates/ModuleAdmin/grades.html
{% extends 'base.html' %}

{% block content %}
    {# siempre lg-7#}

    <div class="col-lg-7">
        <h1>admin grades</h1>
    </div>


{% endblock content %}

templates/ModuleAdmin/students.html
{% extends 'base.html' %}

{% block content %}
    {# siempre lg-7#}

    <div class="col-lg-7">
        <h1>admin students</h1>

            <div class="wall">

            <div class="card">
                <div class="card-body list-div">

                    <div class="">
                        <div class="row list-header">
                            <div class="col-md-2" align="center">
                                Rut
                            </div>
                            <div class="col-md-4" align="center">
                                Nombre
                            </div>
                            <div class="col-md-4" align="center">
                                Apellido
                            </div>
                            <div class="col-md-2" align="center">
                                Rep. Notas
                            </div>
                        </div>
                    </div>

                        {% for student in data %}
                        <div class="">
                            <div class="row list-body">

                                <div class="col-md-2" align="center">
                                    {{ student.rut }}
                                </div>
                                <div class="col-md-4" align="center">
                                    {{ student.first_name }}
                                </div>
                                <div class="col-md-4" align="center">
                                    {{ student.last_name }}
                                </div>
                                <div class="col-md-2" align="center">
                                    <a href="{% url 'module_reports:report-qualifications'  student.id  %}">Reporte</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>


        </div>

    </div>

{% endblock content %}

templates/ModuleAdmin/subjects.html
{% extends 'base.html' %}

{% block content %}
    {# siempre lg-7#}

    <div class="col-lg-7">
        <h1>admin subjects</h1>
    </div>


{% endblock content %}

templates/ModuleAdmin/teachers.html
{% extends 'base.html' %}

{% block content %}
    {# siempre lg-7#}

    <div class="col-lg-7">
        <h1>admin teachers</h1>
    </div>


{% endblock content %}